version: 2
jobs:
  build:
    working_directory: ~/django_spam
    docker:
      - image: python:3.6.0
    steps:
      - checkout
      - run:
            name: Trigger Jobs
            command: |
              # a similar function will liekly get built in into the circleci cli 
              function trigger_job() {
                job_name=$1
                curl -u ${CIRCLE_API_TOKEN}: \
                  -d build_parameters[CIRCLE_JOB]=${job_name} \
                  -d revision=$CIRCLE_SHA1 \
                  https://circleci.com/api/v1.1/project/github/tivix/django-spam/tree/$CIRCLE_BRANCH
              }      
              trigger_job build-python27
              trigger_job build-python35
              trigger_job build-python36
      - deploy:
          name: Echo
          command: echo "I would deploy here"

  # here are our jobs with different Python versions
  build-python27:
       docker:
         - image: python:2.7.13 
       working_directory: ~/django_spam
       steps:
         - run: echo "hello python 2.7.13"
  
  build-python35:
       docker:
         - image: python:3.5.3 
       working_directory: ~/django_spam
       steps:
         - run: echo "hello python 3.5.3"
  
  build-python36:
       docker:
         - image: python:3.6.0
       working_directory: ~/django_spam
       steps:
         - run: echo "hello python 3.6.0"
